import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import BackgroundParticles from "@/components/BackgroundParticles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-background/50 text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* BACKGROUND */}
          <div className="relative">
            <BackgroundParticles />
          </div>

          {/* CONTENT */}
          <header className="z-10">
            <Navbar />
          </header>

          {/* Spacer */}
          <div className="h-20" />

          <main className="max-w-7xl mx-auto">{children}</main>

          <footer className="z-10 py-10 text-center text-sm text-muted-foreground backdrop-blur-xs bg-accent/20">
            © 2025
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
